#!/usr/bin/env bash
# =============================================================================
# Prepare the HOST for the dev container (initializeCommand).
#
# Two jobs, both of which have to happen before the container is created:
#
#  1. .devcontainer/.env, with a freshly generated value for every secret.
#     Compose reads it when it creates the services, which is earlier than any
#     hook running inside the container could write it.
#  2. The bind-mount sources devcontainer.json declares. A bind mount whose
#     source is missing aborts container creation, and Docker would create a
#     directory where a file is expected.
#
# Idempotent: an existing .env is left alone, so a rebuild keeps the password
# the existing database was created with. Pass --force to rotate it, which
# means the old database can no longer be opened.
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$HERE/.env"
S3_TEMPLATE="$HERE/seaweedfs-s3.json.template"
S3_CONFIG="$HERE/seaweedfs-s3.json"

# Every secret this stack needs. FRAPPE_VERSION is not one, but it belongs to
# the same file: switch-frappe-version.sh rewrites it there.
SECRETS=(DB_ROOT_PASSWORD ADMIN_PASSWORD S3_ACCESS_KEY S3_SECRET_KEY KEYCLOAK_PASSWORD)
DEFAULT_FRAPPE_VERSION=v16.16.0

usage() {
    cat <<'EOF'
Usage: init-env.sh [--force] [--print]

Generate .devcontainer/.env with a random value per secret, render
seaweedfs-s3.json from it, and create the host directories the container
bind-mounts. Run automatically as the dev container's initializeCommand.

  --force   replace an existing .env. The database created with the old
            password becomes unreachable
  --print   show the current values (or what would be generated) and exit
  -h        show this help

Exit status: 0 on success or when there was nothing to do, 1 on a bad
argument, 2 when a value could not be generated.
EOF
}

force=false
print_only=false
for arg in "$@"; do
    case "$arg" in
    -h | --help)
        usage
        exit 0
        ;;
    --force) force=true ;;
    --print) print_only=true ;;
    *)
        usage >&2
        exit 1
        ;;
    esac
done

# 32 characters of [A-Za-z0-9]. No openssl dependency, and nothing that would
# need quoting in a .env, a URL or a shell command.
random_secret() {
    local value
    value="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 32 || true)"
    [[ ${#value} -eq 32 ]] || {
        echo "init-env.sh: could not generate a random value from /dev/urandom." >&2
        exit 2
    }
    printf '%s' "$value"
}

write_env() {
    local tmp
    tmp="$(mktemp "${ENV_FILE}.XXXXXX")"
    {
        echo "# Generated by .devcontainer/init-env.sh. Not committed."
        echo "# Rotate with: bash .devcontainer/init-env.sh --force"
        echo "# Rotating invalidates the database created with the old password."
        echo ""
        for name in "${SECRETS[@]}"; do
            echo "${name}=$(random_secret)"
        done
        echo ""
        echo "# The Frappe version install-bench.sh installs. Changed by"
        echo "# development/switch-frappe-version.sh."
        echo "FRAPPE_VERSION=${DEFAULT_FRAPPE_VERSION}"
    } >"$tmp"
    chmod 600 "$tmp"
    mv "$tmp" "$ENV_FILE"
}

# seaweedfs reads its identities from a JSON file, which Compose cannot
# interpolate, so it is rendered here from the template with the same keys.
render_s3_config() {
    [[ -f $S3_TEMPLATE ]] || return 0
    local access secret
    access="$(grep -E '^S3_ACCESS_KEY=' "$ENV_FILE" | cut -d= -f2-)"
    secret="$(grep -E '^S3_SECRET_KEY=' "$ENV_FILE" | cut -d= -f2-)"
    sed -e "s|__S3_ACCESS_KEY__|${access}|" -e "s|__S3_SECRET_KEY__|${secret}|" \
        "$S3_TEMPLATE" >"$S3_CONFIG"
}

if [[ $print_only == true ]]; then
    if [[ -f $ENV_FILE ]]; then
        cat "$ENV_FILE"
    else
        echo "# No .env yet. A run would generate:"
        for name in "${SECRETS[@]}"; do echo "${name}=$(random_secret)"; done
        echo "FRAPPE_VERSION=${DEFAULT_FRAPPE_VERSION}"
    fi
    exit 0
fi

if [[ -f $ENV_FILE && $force == false ]]; then
    echo "init-env.sh: .devcontainer/.env exists, left alone."
else
    write_env
    echo "init-env.sh: wrote .devcontainer/.env with fresh secrets."
fi
render_s3_config

# The bind-mount sources. ~/.gitconfig has to be a file, the other two
# directories: Docker creates a root-owned directory for whichever is missing
# and the mount then fails or shadows the wrong thing.
[[ -f "$HOME/.gitconfig" ]] || {
    touch "$HOME/.gitconfig"
    echo "init-env.sh: created an empty ~/.gitconfig for the mount."
}
mkdir -p "$HOME/.config/gh" "$HOME/.claude"

exit 0
